language: go

go:
  - 1.10.1

sudo: required

services:
  - docker

install: true

script:
  - make test
  - make publish

deploy:
  provider: releases
  file_glob: true
  api_key: "$GITHUB_TOKEN"
  file: "pkg/*.zip"
  skip_cleanup: true
  on:
    tags: true